python train.py -model mlp \
                -gpus 0 \
                -batch_per_gpu 8 \
                -epochs 100 \
                -save_every 5 \
                -out out \
                -cfg config/mlp.yaml \
                -slurm \
                -slurm_ngpus 2 \
                -slurm_nnodes 1 \
                -slurm_nodelist c003 \
                -slurm_partition compute \
                -reset